services:
  webserver81:
    container_name: php
    build:
      context: .
      dockerfile: backend/docker/Dockerfile84
    volumes:
      - ./backend/source:/var/www/html/
      - /var/www/html/tmp
      - /var/www/html/vendor
    ports:
      - 8080:80
      - 8443:443
    environment:
      PHP_MAX_INPUT_VARS: 9999
      DEBUG: true
    networks:
      - network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge
