name: Build Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: instrumentisto/flutter:latest
    steps:
      - name: Configure Git safe directory
        run: git config --global --add safe.directory /usr/local/flutter
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update API host in host_ip.dart
        run: |
          sed -i 's|https://localhost:8443|https://projekt.dawtyl.ovh:8443|' frontend/lib/web_api/host_ip.dart
      - name: Build Flutter Web
        run: |
          cd frontend
          flutter pub get
          flutter build web
          cd build/web
          zip -r ../../../flutter_web_build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter_web_build
          path: flutter_web_build.zip
