name: Build Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: instrumentisto/flutter:latest
    steps:
      - uses: actions/checkout@v4  # To jest konieczne, żeby pobrać kod
      - name: Build Flutter Web
        run: |
          cd frontend
          flutter pub get
          flutter build web
          cd build/web
          zip -r ../../../flutter_web_build.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter_web_build
          path: flutter_web_build.zip
